FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
RUN npm install 
ARG CONTAINER_PORT
EXPOSE ${CONTAINER_PORT}
CMD npm run preview -- --host 0.0.0.0 --port ${CONTAINER_PORT}
