#stage 1
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

#stage 2
FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app .

ARG CONTAINER_PORT
EXPOSE ${CONTAINER_PORT}

CMD npm run preview -- --host 0.0.0.0 --port $CONTAINER_PORT
