FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:18-alpine
RUN npm install -g serve

WORKDIR /app
COPY --from=builder /app/dist ./dist

ARG CONTAINER_PORT
EXPOSE ${CONTAINER_PORT}
CMD serve -s dist -l ${CONTAINER_PORT}
