FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npm install -g serve

COPY . .

RUN npm run build

ARG CONTAINER_PORT
EXPOSE ${CONTAINER_PORT}

CMD serve -s dist -l $CONTAINER_PORT
