FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

ARG CONTAINER_PORT
EXPOSE ${CONTAINER_PORT}

CMD npm run preview -- --host 0.0.0.0 --port $CONTAINER_PORT
