#stage 1
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

#stage 2
WORKDIR /app
FROM node:22-alpine
RUN npm install -g serve
COPY --from=builder /app/dist ./dist

ARG CONTAINER_PORT
EXPOSE ${CONTAINER_PORT}

CMD serve -s dist -l $CONTAINER_PORT
