FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

ARG CONTAINER_PORT
EXPOSE ${CONTAINER_PORT}

CMD ["nginx", "-g", "daemon off;"]